name: "Manual run of the action"
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
  workflow_dispatch:

jobs:
  screenshots:
    runs-on: ubuntu-latest
    outputs:
      result: ${{ steps.screenshot.outputs.scriptResult }}
    steps:
      - uses: karol-brejna-i/webpage-screenshot-action@v1
        id: screenshot
        with:
          url: https://google.com
      - run: |
          ls
  job2:
    runs-on: ubuntu-latest
    needs: screenshots
    steps:
      - run: |
          echo "-----------------------------------"
          echo ${{needs.screenshots.outputs.result}}
          echo "-----------------------------------"