name: "Manual run of the action"
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
  workflow_dispatch:

jobs:
    countParagraphs:
      runs-on: ubuntu-latest
      steps:
        - uses: karol-brejna-i/webpage-screenshot-action@develop
          id: count
          with:
            url: https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions
            scriptBefore: |
              const xpathExpression = 'count(//p)';
              const xpathResult = document.evaluate(xpathExpression, document, null, XPathResult.STRING_TYPE, null);
              result = parseInt(xpathResult).stringValue
        - run: |
            ls
