name: Check dist/

on:
  push:
    branches:
      - develop
      - main
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'
  workflow_dispatch:

jobs:
  check-dist-call:
    uses: actions/reusable-workflows/.github/workflows/check-dist.yml@main