name: "Manual run of the action"
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
  workflow_dispatch:
    inputs:
      url:
        description: 'URL to check'
        required: true
        default: 'https://google.com'
      scriptBefore:
        description: 'Script to run before the check'
        required: false
        type: multiline
        default: 'console.log("Hello world!");'

jobs:
    screenshotLocal:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v3
        - run: npm install
        - name: Run the action
          uses: ./
          id: screenshot
          with:
            url: ${{ github.event.inputs.url }}
            scriptBefore: ${{ github.event.inputs.scriptBefore }}
        - run: |
            ls

    screenshotExternal:
      runs-on: ubuntu-latest
      steps:
        - env:
            URL: ${{ github.event.inputs.url }}
            SCRIPT_BEFORE:
              ${{ github.event.inputs.scriptBefore }}
          run: |
            echo "URL: $URL"
            echo "SCRIPT_BEFORE: $SCRIPT_BEFORE"

        - uses: karol-brejna-i/webpage-screenshot-action@develop
          id: screenshot
          with:
            url: ${{ github.event.inputs.url }}
            scriptBefore: ${{ github.event.inputs.scriptBefore }}
        - run: |
            ls

    multiline:
      runs-on: ubuntu-latest
      steps:
        - env:
            URL: ${{ github.event.inputs.url }}
            SCRIPT_BEFORE:
              ${{ github.event.inputs.scriptBefore }}
          run: |
            echo "URL: $URL"
            echo "SCRIPT_BEFORE: $SCRIPT_BEFORE"

        - uses: karol-brejna-i/webpage-screenshot-action@develop
          id: screenshot
          with:
            url: https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions
            scriptBefore: |
              const headerElement = document.createElement("h1")
              headerElement.innerHTML = "!+!-+!-+!-+!-!";
              const xpathExpression = '//h1';
              const firstChild = document.evaluate(xpathExpression, document, null, XPathResult.FIRST_ORDERED_NODE_TYPE, null).singleNodeValue
              firstChild.parentNode.insertBefore(headerElement, firstChild)

              result = "I made it!";
        - run: |
            ls

    countParagraphs:
      runs-on: ubuntu-latest
      steps:
        - uses: karol-brejna-i/webpage-screenshot-action@develop
          id: count
          with:
            url: https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions
            scriptBefore: |
              const xpathExpression = 'count(//p)';
              const xpathResult = document.evaluate(xpathExpression, document, null, XPathResult.STRING_TYPE, null);
              result = parseInt(xpathResult).stringValue
        - run: |
            ls
