name: "Manual run of the action"
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
  workflow_dispatch:

jobs:
  readme_whole_page:
    runs-on: ubuntu-latest
    steps:
      - run: |
          which google-chrome
          which chromium
          google-chrome --version
          chromium-browser --version

      - uses: karol-brejna-i/webpage-screenshot-action@develop
        with:
          url: https://github.com/karol-brejna-i/webpage-screenshot-action/blob/main/README.md
          output: readme-full-screenshot.png
          mode: wholePage
      - run: |
          ls -lah *.png
      - uses: actions/upload-artifact@v3
        with:
          name: screenshots
          path: ${{ github.workspace }}/*.png

  readme_page:
    runs-on: ubuntu-latest
    steps:
      - run: |
          which google-chrome
          which chromium
          google-chrome --version
          chromium-browser --version

      - uses: karol-brejna-i/webpage-screenshot-action@develop
        with:
          url: https://github.com/karol-brejna-i/webpage-screenshot-action/blob/main/README.md
          mode: page
          output: readme-page-screenshot.png
      - run: |
          ls -lah *.png
      - uses: actions/upload-artifact@v3
        with:
          name: screenshots
          path: ${{ github.workspace }}/*.png
