name: "Manual run of the action"
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
  workflow_dispatch:
    inputs:
      url:
        description: 'URL to check'
        required: true
        default: 'https://google.com'
      scriptBefore:
        description: 'Script to run before the check'
        required: false
        type: multiline
        default: 'console.log("Hello world!");'

jobs:
  screenshotLocal:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: npm install
      - name: Run the action
        uses: ./
        id: screenshot
        with:
          url: ${{ github.event.inputs.url }}
          scriptBefore: ${{ github.event.inputs.scriptBefore }}
      - run: |
          ls

  screenshotExternal:
    runs-on: ubuntu-latest
    steps:
      - env:
          URL: ${{ github.event.inputs.url }}
          SCRIPT_BEFORE:
            ${{ github.event.inputs.scriptBefore }}
        run: |
          echo "URL: $URL"
          echo "SCRIPT_BEFORE: $SCRIPT_BEFORE"

      - uses: karol-brejna-i/webpage-screenshot-action@develop
        id: screenshot
        with:
          url: ${{ github.event.inputs.url }}
          scriptBefore: ${{ github.event.inputs.scriptBefore }}
      - run: |
          ls

  multiline:
    runs-on: ubuntu-latest
    steps:
      - env:
          URL: ${{ github.event.inputs.url }}
          SCRIPT_BEFORE:
            ${{ github.event.inputs.scriptBefore }}
        run: |
          echo "URL: $URL"
          echo "SCRIPT_BEFORE: $SCRIPT_BEFORE"

      - uses: karol-brejna-i/webpage-screenshot-action@develop
        id: screenshot
        with:
          url: https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions
          scriptBefore: |
            const headerElement = document.createElement("h1");
            headerElement.innerHTML = "!+!-+!-+!-+!-!";
            const xpathExpression = '//h1';
            const firstChild = document.evaluate(xpathExpression, document, null, XPathResult.FIRST_ORDERED_NODE_TYPE, null).singleNodeValue;
            firstChild.parentNode.insertBefore(headerElement, firstChild);
            
            result = "I made it!";
      - run: |
          ls

  insert:
    name: Insert DOM element before first <h1>
    runs-on: ubuntu-latest
    steps:
      - uses: karol-brejna-i/webpage-screenshot-action@develop
        id: screenshot
        with:
          url: https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions
          scriptBefore: |
            const headerElement = document.createElement("h1");
            headerElement.innerHTML = "!+!-+!-+!-+!-!";
            const xpathExpression = '//h1';
            const firstChild = document.evaluate(xpathExpression, document, null, XPathResult.FIRST_ORDERED_NODE_TYPE, null).singleNodeValue;
            firstChild.parentNode.insertBefore(headerElement, firstChild);
            
            result = "I made it!";
      - run: |
          ls

  countParagraphs:
    name: Count <p> elements
    runs-on: ubuntu-latest
    steps:
      - uses: karol-brejna-i/webpage-screenshot-action@develop
        id: count
        with:
          url: https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions
          scriptBefore: |
            const xpathExpression = 'count(//p)';
            const xpathResult = document.evaluate(xpathExpression, document, null, XPathResult.STRING_TYPE, null);
            result = parseInt(xpathResult.stringValue);
      - run: |
          ls

  checkText:
    name: Check if given test is present in the page (here, we are looking for 'World')
    runs-on: ubuntu-latest
    steps:
      - uses: karol-brejna-i/webpage-screenshot-action@develop
        id: count
        with:
          url: https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions
          scriptBefore: |
            if (element.innerText.includes('World')) { 
              console.log("Found!");
              result = true;
            } else {
              console.log("Not found!");
              result = false;
            }
      - run: |
          ls

  localFile:
    name: Use local file (html file in the local filesystem)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        id: checkout
        with:
          ref: develop
      - run: |
          ls examples/
          cat examples/simple.html
      - uses: karol-brejna-i/webpage-screenshot-action@develop
        id: openLocalFile
        with:
          url: file://${PWD}/examples/simple.html
      - run: |
          ls
