name: "Browser scripting - xpath expressionsl"
run-name: ${{ github.actor }} is trying xpath expressions 🚀
on:
  workflow_dispatch:

jobs:
  insert:
    name: Insert DOM element before first <h1>
    runs-on: ubuntu-latest
    steps:
      - uses: karol-brejna-i/webpage-screenshot-action@v1.0.0
        id: screenshot
        with:
          url: https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions
          scriptBefore: |
            const headerElement = document.createElement("h1");
            headerElement.innerHTML = "!+!-+!-+!-+!-!";
            const xpathExpression = '//h1';
            const firstChild = document.evaluate(xpathExpression, document, null, XPathResult.FIRST_ORDERED_NODE_TYPE, null).singleNodeValue;
            firstChild.parentNode.insertBefore(headerElement, firstChild);
            
            result = "I made it!";
      - run: |
          ls

  count_paragraphs:
    name: Count <p> elements
    runs-on: ubuntu-latest
    steps:
      - uses: karol-brejna-i/webpage-screenshot-action@v1.0.0
        id: count
        with:
          url: https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions
          scriptBefore: |
            const xpathExpression = 'count(//p)';
            const xpathResult = document.evaluate(xpathExpression, document, null, XPathResult.STRING_TYPE, null);
            result = parseInt(xpathResult.stringValue);
      - run: |
          ls
