name: "Use different targets"
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
  workflow_dispatch:
    inputs:
      url:
        description: 'URL to check'
        required: true
        default: 'https://github.com/karol-brejna-i/webpage-screenshot-action/blob/main/README.md'
      scriptBefore:
        description: 'Script to run before the check'
        required: false
        type: multiline
        default: 'console.log("Hello world!"); result=42;'

jobs:
  screenshot_external:
    runs-on: ubuntu-latest
    steps:
      - uses: karol-brejna-i/webpage-screenshot-action@develop
        id: screenshot
        with:
          url: ${{ github.event.inputs.url }}
          scriptBefore: ${{ github.event.inputs.scriptBefore }}
      - run: |
          ls -lah

  local_file:
    name: Use local file (html file in the local filesystem)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        id: checkout
        with:
          ref: main
      - run: |
          ls examples/
          cat examples/simple.html
      - uses: karol-brejna-i/webpage-screenshot-action@develop
        id: openLocalFile
        with:
          url: file://${{github.workspace}}/examples/simple.html
      - run: |
          ls -lah
      - uses: actions/upload-artifact@v3
        with:
          name: screenshots
          path: ${{ github.workspace }}/*.png
